[package]
name = "searcher"
version = "0.1.0"
edition = "2021"

[dependencies]
base_tool = { path = "../base_tool" }
database = { path = "../database" }
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
