[package]
name = "downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }

anyhow = "1"
once_cell = "1"
base64 = "0.21"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
