[package]
name = "database"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
once_cell = "1"
sea-orm = { version = "0.11", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = "0.11"
serde = { version = "1", features = ["derive"] }
