[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
poem = { version = "1", features = ["embed"] }
rust-embed = { version = "6", features = ["debug-embed"] }
serde = { version = "1", features = ["derive"] }
