[package]
name = "web_server"
version = "0.1.0"
edition = "2021"

[dependencies]
base_tool = { path = "../base_tool" }
poem = { version = "1.3", features = ["embed"] }
rust-embed = { version = "6.3", features = ["debug-embed"] }
serde = { version = "1.0", features = ["derive"] }
