[package]
name = "http-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
once_cell = "1"
quick-xml = { version = "0.28", features = ["serialize"] }
reqwest = { version = "0.11", features = ["cookies", "json"] }
serde = "1"
scrapers = { path = "../scrapers" }
