[package]
name = "film_info"
version = "0.1.0"
edition = "2021"

[dependencies]
base_tool = { path = "../base_tool" }
database = { path = "../database" }
reqwest = { version = "0.11", features = ["json"] }
