[package]
name = "value-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
cssparser = "0.*"
ego-tree = "0.6"
html5ever = "0.26"
once_cell = "1"
quick-xml = "0.28"
scraper = "0.16"
selectors = "0.24"
serde = "1"
serde_json = "1"
